version: '2'

services:
    postgres:
      image: 'postgres'
      volumes:
        - 'postgres:/var/lib/postgresql/data'
    
    redis:
      image: 'redis:4.0.10-alpine'
      command: redis-server
      ports:
        - '6379:6379'
      volumes:
        - 'redis:/var/lib/redis/data'

    jobs:
      depends_on:
        - 'postgres'
        - 'redis'
        - 'website'
      build: .
      command: bash start_jobs.sh
      volumes_from:
        - box
      env_file:
        - '.env-prod'

    app:
        depends_on:
          - 'postgres'
          - 'redis'
        build: .
        command: bash start.sh
        ports:
          - '3000:3000'
        volumes_from:
          - box
        env_file:
          - '.env-prod'

    box:
      image: busybox
      volumes:
        - '/box'

volumes:
  redis:
  postgres:
  box: