version: '2'

services:
    postgres:
      image: 'postgres'
      volumes:
        - 'postgres:/var/lib/postgresql/data'
    
    redis:
      image: 'redis:4.0.10-alpine'
      command: redis-server
      ports:
        - '6379:6379'
      volumes:
        - 'redis:/var/lib/redis/data'

    jobs:
      depends_on:
        - 'postgres'
        - 'redis'
        - 'app'
      build: .
      command: bash start_jobs.sh
      volumes:
        - '.:/app'
        - 'box/:/box'

    app:
        depends_on:
          - 'postgres'
          - 'redis'
        build: .
        command: bash start.sh
        ports:
          - '3000:3000'
        volumes:
          - '.:/app'
          - 'box/:/box'

    mailcatcher:
      image: yappabe/mailcatcher
      ports:
        - 1025:1025
        - 1080:1080

volumes:
  redis:
  postgres:
  box: